# 서버 포트 설정
server:
  port: 8080

# database 연동 설정
spring:
  datasource:
    hikari:
#      platform: mysql
#      driver-class-name: org.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://54.180.149.160:3306/dashboard?serverTimezone=UTC&characterEncoding=UTF-8
      username: will
      password: will
#    hikari:

#      platform: mysql

  #    driver-class-name: org.mariadb.jdbc.Driver
  #    url: jdbc:mariadb://localhost:3306/dashboard
  #    username: will
  #    password: will
  thymeleaf:
    cache: false

  # spring data jpa 설정
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    **은 하위 폴더 레벨에 상관없이 모든 경로를 뜻하며, *는 아무 이름이나 와도 된다는것을 뜻한다.
  mybatis:
    mapper-locations: classpath:mybatis/**/*.xml,classpath:mybatis/board/*.xml
    config-locations: classpath:mybatis/mybatis_config.xml
